---
abstract: 'Mirror Configuration and Auto-Discovery'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Temp: 0.19
  LWP::Online: 1.07
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Mirror::URI
name: Mirror-URI
no_index:
  directory:
    - inc
    - t
requires:
  JSON: 2.13
  LWP::Simple: 1.41
  Params::Util: 1.00
  Parse::CPAN::Meta: 1.39
  Time::HiRes: 1.9714
  Time::Local: 1.13
  URI: 1.28
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Mirror-URI
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Mirror-URI
version: 0.90
